stages:
  - test
  - docker build
  - docker candidate
  - docker release

variables:
  IMG_NAME: $(cat app/name)
  IMG_VERSION: $(cat app/version)

pylint:
  stage: test
  image: python:3.10-slim-buster
  before_script:
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt
  script:
    - pylint ./app
  only:
    - candidate
    - main

Docker build:
  stage: docker build
  image: docker
  services:
    - docker:dind
  script:
    - docker build -t ebarsukov/${IMG_NAME}:test  -f docker/Dockerfile .
    - docker push ebarsukov/${IMG_NAME}:test
  before_script:
    - echo -n ${DOCKER_PASS} | docker login -u ebarsukov --password-stdin
  only:
    - candidate
    - main

docker push candidate:
  stage: docker candidate
  image: docker
  services:
    - docker:dind
  script:
    - docker pull robocafe/${IMG_NAME}:test
    - docker tag ebarsukov/${IMG_NAME}:test ebarsukov/${IMG_NAME}:candidate
    - docker push ebarsukov/${IMG_NAME}:candidate
  before_script:
    - echo -n ${DOCKER_PASS} | docker login -u ebarsukov --password-stdin
  only:
    - candidate

docker push latest:
  stage: docker release
  image: docker
  services:
    - docker:dind
  script:
    - docker pull robocafe/${IMG_NAME}:test
    - docker tag ebarsukov/${IMG_NAME}:test ebarsukov/${IMG_NAME}:latest
    - docker push ebarsukov/${IMG_NAME}:latest
  before_script:
    - echo -n ${DOCKER_PASS} | docker login -u ebarsukov --password-stdin
  only:
    - tag

docker push version:
  stage: docker release
  image: docker
  services:
    - docker:dind
  script:
    - docker pull robocafe/${IMG_NAME}:test
    - docker tag ebarsukov/${IMG_NAME}:test ebarsukov/${IMG_NAME}:${IMG_VERSION}
    - docker push ebarsukov/${IMG_NAME}:${IMG_VERSION}
  before_script:
    - echo -n ${DOCKER_PASS} | docker login -u ebarsukov --password-stdin
  only:
    - tag
