services:

  dobot-arm-connector:
    image: gpt-telegram-asystant:latest
    restart: unless-stopped
    volumes:
      - ./gpt-telegram-asystant:/gpt-telegram-asystant

    environment:
      OPENAI_API_KEY: sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      OPENAI_API_MODEL: gpt-3.5-turbo-0301
      OPENAI_CHAT_LIFETIME_SEC: 1800
      OPENAI_TEMPERATURE: 0.5
      OPENAI_MAX_TOKENS: 100
      OPENAI_CHAT_USER_PRESET: ''
      OPENAI_CHAT_SYSTEM_PRESET: "You are an intellectual assistant, The name of your interlocutor is {user_name}"
      TELEGRAM_BOT_TOKEN: xxxxxxxxxx:xx-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      BUFFER_MSG_LIFETIME_SEC: 180
      WORKDIR: ./gpt-telegram-asystant
